# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clipit < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/omuomugin/clipit/releases/download/v0.0.1/clipit_Darwin_x86_64.tar.gz"
      sha256 "82dbf94df8beb9310ea2f7f1e17f4869f7af42b23301572ccc82e711c6ce1f9b"

      def install
        bin.install "clipit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/omuomugin/clipit/releases/download/v0.0.1/clipit_Darwin_arm64.tar.gz"
      sha256 "18153d19d867d7ea45b1af04e45b4c5effb4364dcf63d564eead019a61e1d98e"

      def install
        bin.install "clipit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/omuomugin/clipit/releases/download/v0.0.1/clipit_Linux_arm64.tar.gz"
      sha256 "0dbc008f9b25851544884189eeda013dd9e268b0bbec589175624e072d328ce3"

      def install
        bin.install "clipit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/omuomugin/clipit/releases/download/v0.0.1/clipit_Linux_x86_64.tar.gz"
      sha256 "d5cc15d00ad4adac4c4d784f543c372242427dde3f547c014eb118ec56c8583e"

      def install
        bin.install "clipit"
      end
    end
  end
end
